# Before you start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [47]:
import numpy as np
import pandas as pd


# Challenge 1 - Exploring the Data

In this challenge, we will examine all salaries of employees of the City of Chicago. We will start by loading the dataset and examining its contents. Please, load the data using Ironhack's database (db: employees, table: employees_advanced).

In [48]:
data = pd.read_csv('./Current_Employee_Names__Salaries__and_Position_Titles.csv')
data.columns = [i.lower().replace(' ', '_') for i in data.columns]
data.shape

(32658, 8)

Examine the `salaries` dataset using the `head` function below.

In [49]:
data.head()

name      job_titles department full_or_part-time  \
0  ALLISON,  PAUL W      LIEUTENANT       FIRE                 F   
1   BRUNO,  KEVIN D        SERGEANT     POLICE                 F   
2   COOPER,  JOHN E  LIEUTENANT-EMT       FIRE                 F   
3  CRESPO,  VILMA I      STAFF ASST        LAW                 F   
4  DOLAN,  ROBERT J        SERGEANT     POLICE                 F   

  salary_or_hourly  typical_hours annual_salary hourly_rate  
0           Salary            NaN    $107790.00         NaN  
1           Salary            NaN    $104628.00         NaN  
2           Salary            NaN    $114324.00         NaN  
3           Salary            NaN     $76932.00         NaN  
4           Salary            NaN    $111474.00         NaN

We see from looking at the `head` function that there is quite a bit of missing data. Let's examine how much missing data is in each column. Produce this output in the cell below

In [50]:
data.isna().sum()

name                     0
job_titles               0
department               0
full_or_part-time        0
salary_or_hourly         0
typical_hours        24775
annual_salary         7883
hourly_rate          24775
dtype: int64

Let's also look at the count of hourly vs. salaried employees. Write the code in the cell below

In [51]:
data['salary_or_hourly'].value_counts()

Salary    24775
Hourly     7883
Name: salary_or_hourly, dtype: int64

What this information indicates is that the table contains information about two types of employees - salaried and hourly. Some columns apply only to one type of employee while other columns only apply to another kind. This is why there are so many missing values. Therefore, we will not do anything to handle the missing values.

There are different departments in the city. List all departments and the count of employees in each department.

In [52]:
data['department'].value_counts()

POLICE                   12973
FIRE                      4800
STREETS & SAN             2194
OEMC                      2044
WATER MGMNT               1878
AVIATION                  1612
TRANSPORTN                1103
GENERAL SERVICES           972
PUBLIC LIBRARY             932
FAMILY & SUPPORT           621
FINANCE                    575
HEALTH                     516
LAW                        405
CITY COUNCIL               400
BUILDINGS                  266
COMMUNITY DEVELOPMENT      214
BUSINESS AFFAIRS           168
BOARD OF ELECTION          112
DoIT                       101
PROCUREMENT                 86
MAYOR'S OFFICE              85
CITY CLERK                  85
CULTURAL AFFAIRS            76
ANIMAL CONTRL               73
HUMAN RESOURCES             68
INSPECTOR GEN               63
IPRA                        56
BUDGET & MGMT               44
ADMIN HEARNG                38
DISABILITIES                29
TREASURER                   24
HUMAN RELATIONS             17
COPA    

# Challenge 2 - Hypothesis Tests

In this section of the lab, we will test whether the hourly wage of all hourly workers is significantly different from $30/hr. Import the correct one sample test function from scipy and perform the hypothesis test for a 95% two sided confidence interval.

In [53]:
import scipy as sp

In [54]:
data_hour = data[~(data['hourly_rate'].isna())]
data_hour.head()



name                   job_titles        department  \
11       FITCH,  JORDAN M                    LAW CLERK               LAW   
54      ABASCAL,  REECE E  TRAFFIC CONTROL AIDE-HOURLY              OEMC   
56  ABBATACOLA,  ROBERT J          ELECTRICAL MECHANIC          AVIATION   
57     ABBATE,  JOSEPH L       POOL MOTOR TRUCK DRIVER     STREETS & SAN   
60       ABBOTT,  BETTY L           FOSTER GRANDPARENT  FAMILY & SUPPORT   

   full_or_part-time salary_or_hourly  typical_hours annual_salary hourly_rate  
11                 F           Hourly           35.0           NaN      $14.51  
54                 P           Hourly           20.0           NaN      $19.66  
56                 F           Hourly           40.0           NaN      $46.10  
57                 F           Hourly           40.0           NaN      $35.60  
60                 P           Hourly           20.0           NaN       $2.65

In [55]:
data_hour['hourly_rate'] = data_hour['hourly_rate'].str.replace('$', '', regex = True).astype('float64')


C:\Users\Phillip\AppData\Local\Temp/ipykernel_24412/2937427202.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_hour['hourly_rate'] = data_hour['hourly_rate'].str.replace('$', '', regex = True).astype('float64')


In [56]:
data_hour.head()

name                   job_titles        department  \
11       FITCH,  JORDAN M                    LAW CLERK               LAW   
54      ABASCAL,  REECE E  TRAFFIC CONTROL AIDE-HOURLY              OEMC   
56  ABBATACOLA,  ROBERT J          ELECTRICAL MECHANIC          AVIATION   
57     ABBATE,  JOSEPH L       POOL MOTOR TRUCK DRIVER     STREETS & SAN   
60       ABBOTT,  BETTY L           FOSTER GRANDPARENT  FAMILY & SUPPORT   

   full_or_part-time salary_or_hourly  typical_hours annual_salary  \
11                 F           Hourly           35.0           NaN   
54                 P           Hourly           20.0           NaN   
56                 F           Hourly           40.0           NaN   
57                 F           Hourly           40.0           NaN   
60                 P           Hourly           20.0           NaN   

    hourly_rate  
11        14.51  
54        19.66  
56        46.10  
57        35.60  
60         2.65

In [57]:
data_hour['hourly_rate'].mean()

32.86819231257292

In [58]:
from scipy.stats import ttest_1samp

stat, pval = ttest_1samp(data_hour['hourly_rate'], 30)

# H0 : Hourly Wage(mean) == 30$
# H1 : Hourly Wage(mean) != 30%

In [59]:
print('stat is  ', stat)
print('pvalue for the two-tailed test is ', pval)

stat is   21.003532193332216
pvalue for the two-tailed test is  2.4048011351057683e-95


# since the pvalue for the two tailed test is way lower than 0.05 we have to reject the H0 Hypothesis and have evidence to assume H1 is correct

We are also curious about salaries in the police force. The chief of police in Chicago claimed in a press briefing that salaries this year are higher than last year's mean of $86000/year a year for all salaried employees. Test this one sided hypothesis using a 95% confidence interval.

Hint: A one tailed test has a p-value that is half of the two tailed p-value. If our hypothesis is greater than, then to reject, the test statistic must also be positive.

In [60]:
data_annual = data[~(data['annual_salary'].isna())]
data_annual.head()


name      job_titles department full_or_part-time  \
0  ALLISON,  PAUL W      LIEUTENANT       FIRE                 F   
1   BRUNO,  KEVIN D        SERGEANT     POLICE                 F   
2   COOPER,  JOHN E  LIEUTENANT-EMT       FIRE                 F   
3  CRESPO,  VILMA I      STAFF ASST        LAW                 F   
4  DOLAN,  ROBERT J        SERGEANT     POLICE                 F   

  salary_or_hourly  typical_hours annual_salary hourly_rate  
0           Salary            NaN    $107790.00         NaN  
1           Salary            NaN    $104628.00         NaN  
2           Salary            NaN    $114324.00         NaN  
3           Salary            NaN     $76932.00         NaN  
4           Salary            NaN    $111474.00         NaN

In [61]:
data_annual['annual_salary'] = data_annual['annual_salary'].str.replace('$', '', regex = True).astype('float64')


C:\Users\Phillip\AppData\Local\Temp/ipykernel_24412/2202351111.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_annual['annual_salary'] = data_annual['annual_salary'].str.replace('$', '', regex = True).astype('float64')


In [62]:
data_annual.head()

name      job_titles department full_or_part-time  \
0  ALLISON,  PAUL W      LIEUTENANT       FIRE                 F   
1   BRUNO,  KEVIN D        SERGEANT     POLICE                 F   
2   COOPER,  JOHN E  LIEUTENANT-EMT       FIRE                 F   
3  CRESPO,  VILMA I      STAFF ASST        LAW                 F   
4  DOLAN,  ROBERT J        SERGEANT     POLICE                 F   

  salary_or_hourly  typical_hours  annual_salary hourly_rate  
0           Salary            NaN       107790.0         NaN  
1           Salary            NaN       104628.0         NaN  
2           Salary            NaN       114324.0         NaN  
3           Salary            NaN        76932.0         NaN  
4           Salary            NaN       111474.0         NaN

In [63]:
data_annual['annual_salary'].mean()

87512.78024137241

In [64]:
stat, pval = ttest_1samp(data_annual['annual_salary'], 86000)


# H0 : annual_salary(mean) == 86000$
# H1 : annual_salary(mean) != 86000%

In [65]:
print('stat is  ', stat)
print('pvalue for the one-tailed test is ', pval/2)

stat is   11.579263110111727
pvalue for the one-tailed test is  3.1532773354581996e-31


# since the pvalue for the one tailed test is way lower than 0.05 we have to reject the H0 Hypothesis and have evidence to assume H1 is correct

Using the `crosstab` function, find the department that has the most hourly workers. 

In [66]:
data_cross = pd.crosstab(data_hour['department'], data_hour['salary_or_hourly'], margins = False)
data_cross.reset_index()
data_cross.sort_values(by=['Hourly'],ascending=False)



salary_or_hourly       Hourly
department                   
STREETS & SAN            1873
WATER MGMNT              1512
OEMC                     1212
AVIATION                 1056
GENERAL SERVICES          767
TRANSPORTN                707
FAMILY & SUPPORT          300
PUBLIC LIBRARY            224
CITY COUNCIL               52
LAW                        44
FINANCE                    43
POLICE                     32
ANIMAL CONTRL              16
CULTURAL AFFAIRS           10
BUSINESS AFFAIRS            8
MAYOR'S OFFICE              7
COMMUNITY DEVELOPMENT       4
PROCUREMENT                 4
HEALTH                      4
CITY CLERK                  3
FIRE                        2
HUMAN RESOURCES             1
BUDGET & MGMT               1
TREASURER                   1

The workers from the department with the most hourly workers have complained that their hourly wage is less than $35/hour. Using a one sample t-test, test this one-sided hypothesis at the 95% confidence level.

In [67]:
data_streets = data_hour[(data_hour['department']=='STREETS & SAN')]
data_streets

name               job_titles     department  \
57         ABBATE,  JOSEPH L   POOL MOTOR TRUCK DRIVER  STREETS & SAN   
73      ABDUL-SHAKUR,  TAHIR     GENERAL LABORER - DSS  STREETS & SAN   
76     ABERCROMBIE,  TIMOTHY        MOTOR TRUCK DRIVER  STREETS & SAN   
85        ABRAMS,  DANIELLE T       SANITATION LABORER  STREETS & SAN   
88          ABRAMS,  SAMUEL A  POOL MOTOR TRUCK DRIVER  STREETS & SAN   
...                       ...                      ...            ...   
32582         ZIZUMBO,  LUIS        MOTOR TRUCK DRIVER  STREETS & SAN   
32623        ZUMMO,  ROBERT J       MOTOR TRUCK DRIVER  STREETS & SAN   
32624     ZUNICH,  JONATHAN G       SANITATION LABORER  STREETS & SAN   
32631        ZUNIGA,  THOMAS     GENERAL LABORER - DSS  STREETS & SAN   
32637       ZURAWSKI,  MAC Z        SANITATION LABORER  STREETS & SAN   

      full_or_part-time salary_or_hourly  typical_hours annual_salary  \
57                    F           Hourly           40.0           NaN   
73                    F           Hourly           40.0           NaN   
76                    F           Hourly           40.0           NaN   
85                    F           Hourly           40.0           NaN   
88                    F           Hourly           40.0           NaN   
...                 ...              ...            ...           ...   
32582                 F           Hourly           40.0           NaN   
32623                 F           Hourly           40.0           NaN   
32624                 F           Hourly           40.0           NaN   
32631                 F           Hourly           40.0           NaN   
32637                 F           Hourly           40.0           NaN   

       hourly_rate  
57           35.60  
73           20.77  
76           35.60  
85           36.21  
88           35.60  
...            ...  
32582        35.60  
32623        35.60  
32624        36.21  
32631        21.43  
32637        36.21  

[1873 rows x 8 columns]

In [68]:
data_streets.hourly_rate.mean()

34.06726641751145

In [69]:
stat, pval = ttest_1samp(data_streets.hourly_rate, 35)


# H0 : Hourly Wage(mean) == 35$
# H1 : Hourly Wage(mean) != 35%

In [70]:
print('stat is  ', stat)
print('pvalue for the one-tailed test is ', pval/2)

stat is   -7.172610090911691
pvalue for the one-tailed test is  5.276243152130208e-13


# since the pvalue for the one tailed test is way lower than 0.05 we have to reject the H0 Hypothesis and have evidence to assume H1 is correct

# Challenge 3: To practice - Constructing Confidence Intervals

While testing our hypothesis is a great way to gather empirical evidence for accepting or rejecting the hypothesis, another way to gather evidence is by creating a confidence interval. A confidence interval gives us information about the true mean of the population. So for a 95% confidence interval, we are 95% sure that the mean of the population is within the confidence interval. 
).

To read more about confidence intervals, click [here](https://en.wikipedia.org/wiki/Confidence_interval).


In the cell below, we will construct a 95% confidence interval for the mean hourly wage of all hourly workers. 

The confidence interval is computed in SciPy using the `t.interval` function. You can read more about this function [here](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.t.html).

To compute the confidence interval of the hourly wage, use the 0.95 for the confidence level, number of rows - 1 for degrees of freedom, the mean of the sample for the location parameter and the standard error for the scale. The standard error can be computed using [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html) function in SciPy.

In [71]:
data_hour.head()

name                   job_titles        department  \
11       FITCH,  JORDAN M                    LAW CLERK               LAW   
54      ABASCAL,  REECE E  TRAFFIC CONTROL AIDE-HOURLY              OEMC   
56  ABBATACOLA,  ROBERT J          ELECTRICAL MECHANIC          AVIATION   
57     ABBATE,  JOSEPH L       POOL MOTOR TRUCK DRIVER     STREETS & SAN   
60       ABBOTT,  BETTY L           FOSTER GRANDPARENT  FAMILY & SUPPORT   

   full_or_part-time salary_or_hourly  typical_hours annual_salary  \
11                 F           Hourly           35.0           NaN   
54                 P           Hourly           20.0           NaN   
56                 F           Hourly           40.0           NaN   
57                 F           Hourly           40.0           NaN   
60                 P           Hourly           20.0           NaN   

    hourly_rate  
11        14.51  
54        19.66  
56        46.10  
57        35.60  
60         2.65

In [73]:
confidence_level = 0.95
degrees_freedom = len(data_hour['hourly_rate']) - 1  # or, for large values of sample size, just use that
sample_mean = np.mean(data_hour['hourly_rate'])
# note that we use the standard error of the sample 
# as an estimate of the standard error of the population (which is used in the theoretical formula)
sample_standard_error = sp.stats.sem(data_hour['hourly_rate']) # sem = standard error of the mean = std(mean)/sqrt(samplesize)

confidence_interval = sp.stats.t.interval(confidence_level, 
                                             degrees_freedom, 
                                             sample_mean, 
                                             sample_standard_error)

In [74]:
print( 'confidence interval is ', confidence_interval, '.' )

confidence interval is  (32.60050319432687, 33.135881430818976) .


In [75]:
data_hour['hourly_rate'].mean()

32.86819231257292

Now construct the 95% confidence interval for all salaried employeed in the police in the cell below.

In [88]:
data_police = data[(data['department']=='POLICE')]
data_police['annual_salary'] = data_police['annual_salary'].str.replace('$', '', regex = True).astype('float64')
data_police = data_police[~(data_police['annual_salary'].isna())]
data_police


C:\Users\Phillip\AppData\Local\Temp/ipykernel_24412/466355951.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_police['annual_salary'] = data_police['annual_salary'].str.replace('$', '', regex = True).astype('float64')


name      job_titles department full_or_part-time  \
1            BRUNO,  KEVIN D        SERGEANT     POLICE                 F   
4           DOLAN,  ROBERT J        SERGEANT     POLICE                 F   
7            ELKINS,  ERIC J        SERGEANT     POLICE                 F   
8           ESTRADA,  LUIS F  POLICE OFFICER     POLICE                 F   
9            EWING,  MARIE A       CLERK III     POLICE                 F   
...                      ...             ...        ...               ...   
32652       ZYGMUNT,  DAWID   POLICE OFFICER     POLICE                 F   
32653     ZYGOWICZ,  PETER J  POLICE OFFICER     POLICE                 F   
32654  ZYLINSKA,  KATARZYNA   POLICE OFFICER     POLICE                 F   
32655      ZYMANTAS,  MARK E  POLICE OFFICER     POLICE                 F   
32656    ZYRKOWSKI,  CARLO E  POLICE OFFICER     POLICE                 F   

      salary_or_hourly  typical_hours  annual_salary hourly_rate  
1               Salary            NaN       104628.0         NaN  
4               Salary            NaN       111474.0         NaN  
7               Salary            NaN       104628.0         NaN  
8               Salary            NaN        96060.0         NaN  
9               Salary            NaN        53076.0         NaN  
...                ...            ...            ...         ...  
32652           Salary            NaN        48078.0         NaN  
32653           Salary            NaN        90024.0         NaN  
32654           Salary            NaN        48078.0         NaN  
32655           Salary            NaN        87006.0         NaN  
32656           Salary            NaN        93354.0         NaN  

[12941 rows x 8 columns]

In [89]:
confidence_level = 0.95
degrees_freedom = len(data_police['annual_salary']) - 1  # or, for large values of sample size, just use that
sample_mean = np.mean(data_police['annual_salary'])
# note that we use the standard error of the sample 
# as an estimate of the standard error of the population (which is used in the theoretical formula)
sample_standard_error = sp.stats.sem(data_police['annual_salary']) # sem = standard error of the mean = std(mean)/sqrt(samplesize)

confidence_interval = sp.stats.t.interval(confidence_level, 
                                             degrees_freedom, 
                                             sample_mean, 
                                             sample_standard_error)

In [90]:
print( 'confidence interval is ', confidence_interval, '.' )

confidence interval is  (87549.78923170577, 88122.26146607645) .


In [81]:
data_police['annual_salary'].mean()

87836.02534889111

# Bonus Challenge - Hypothesis Tests of Proportions

Another type of one sample test is a hypothesis test of proportions. In this test, we examine whether the proportion of a group in our sample is significantly different than a fraction. 

You can read more about one sample proportion tests [here](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/SAS/SAS6-CategoricalData/SAS6-CategoricalData2.html).

In the cell below, use the `proportions_ztest` function from `statsmodels` to perform a hypothesis test that will determine whether the number of hourly workers in the City of Chicago is significantly different from 25% at the 95% confidence level.

In [92]:
data.isna().sum() # no NaN in salary_or_hourly, whole dataset has information on what we want to analyze

name                     0
job_titles               0
department               0
full_or_part-time        0
salary_or_hourly         0
typical_hours        24775
annual_salary         7883
hourly_rate          24775
dtype: int64

In [93]:
data.shape # a total of 32658 workers

(32658, 8)

In [91]:
data.salary_or_hourly.value_counts()

Salary    24775
Hourly     7883
Name: salary_or_hourly, dtype: int64

In [100]:
32658*0.25 # manual checking of the distribution, value is prett close to the actual distribution

8164.5

We expect 25% of the workers to be hourly workes , so our null hypothesis is: 25% of the workers are hourly workers
Our alternative hypothesis is: more than 25% of the workers are hourly workers
We sampled 32658 rows, and found 7883 are hourly workers
We use a 1-sample z-test to check if the sample allows us to accept or reject the null hypothesis

In [109]:
from statsmodels.stats.proportion import proportions_ztest
significance = 0.05
sample_success = 7883
sample_size = 32658
null_hypothesis = 0.25
stat, p_value = proportions_ztest(count=sample_success, nobs=sample_size, value=null_hypothesis, alternative='larger')

print(stat)
print(p_value)

-3.6401610358268113
0.9998637662093031


In [ ]:
# p value is very close to 1, this means we keep our null hypothesis : 25% of the workers are hourly workers, we discard the hypothesis that there is a significant difference